version: '3.3'

services:

  demo-audio-chat:
    image: 127.0.0.1:5000/demo-audio-chat:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3040:3000/tcp"
      - "3040:3000/udp"
    environment:
      - REACT_APP_GEMINI_API_KEY
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any 